# Generated by Django 5.1.2 on 2025-01-25 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User
from django.utils.timezone import now

def create_default_post_states(apps, schema_editor):
    PostState = apps.get_model('api', 'PostState')  # Reemplaza 'your_app_name' con el nombre de tu app
    PostState.objects.get_or_create(name='verified')
    PostState.objects.get_or_create(name='not_verified')
    PostState.objects.get_or_create(name='rejected')
    
    # Crear un superusuario si no existe
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@admin.com',
            password='admin123',
            last_login=now()
        )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_image_alter_review_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PostCategory',
        ),
        migrations.AddField(
            model_name='reportcategory',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reportcategory',
            name='name',
            field=models.CharField(default='ALGo', max_length=30),
        ),
        migrations.CreateModel(
            name='Valoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoration', models.BooleanField(default=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('review', 'user')},
            },
        ),
        migrations.RunPython(create_default_post_states),
    ]
