# Generated by Django 5.1.2 on 2025-01-27 18:42

from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations, models
from django.contrib.contenttypes.models import ContentType

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_category_postcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='reportcategory',
            name='type_categorie',
            field=models.CharField(choices=[('reviews', 'Reviews'), ('posts', 'Posts'), ('users', 'Users')], max_length=20),
        ),
    ]
