# Generated by Django 5.1.2 on 2024-10-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='posts', to='api.review'),
        ),
    ]
