# Generated by Django 5.1.2 on 2025-01-27 18:42

from django.db import migrations, models

def create_report_categories(apps, schema_editor):
    ReportCategory = apps.get_model('api', 'ReportCategory')
    
    ReportCategory.objects.get_or_create(name='Contenido sexual')
    ReportCategory.objects.get_or_create(name='Contenido violento o repulsivo')
    ReportCategory.objects.get_or_create(name='Contenido abusivo')
    ReportCategory.objects.get_or_create(name='Acoso o bullying')
    ReportCategory.objects.get_or_create(name='Actividades peligrosas o dañinas')
    ReportCategory.objects.get_or_create(name='Información errónea')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_category_postcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    
    migrations.RunPython(create_report_categories),
    ]
