# Generated by Django 5.1.2 on 2024-10-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reviews',
        ),
    ]
