# Generated by Django 5.1.2 on 2025-01-27 20:52

from django.db import migrations, models

def create_report_categories_reviews(apps, schema_editor):
    ReportCategory = apps.get_model('api', 'ReportCategory')

    categories = [
        'Contenido sexual',
        'Contenido violento o repulsivo',
        'Contenido abusivo',
        'Acoso o bullying',
        'Actividades peligrosas o dañinas',
        'Información errónea',
    ]

    for category in categories:
        ReportCategory.objects.get_or_create(name=category, type_categorie='reviews')
        
def create_report_categories_posts(apps, schema_editor):
    ReportCategory = apps.get_model('api', 'ReportCategory')

    categories = [
        'Contenido sexual',
        'Contenido abusivo o que incita al odio',
        'Acoso o bullying',
        'Actividades peligrosas o dañinas',
        'Información errónea',
        'Abuso de menores',
        'Fomenta el terrorismo',
        'Contenido engañoso o spam',
        'Problema legal'
    ]

    for category in categories:
        ReportCategory.objects.get_or_create(name=category, type_categorie='posts')
        
def create_report_categories_users(apps, schema_editor):
    ReportCategory = apps.get_model('api', 'ReportCategory')

    categories = [
        'Acoso y cyberbullying',
        'Privacidad',
        'Suplantación de identidad',
        'Amenazas violentas',
        'Menores en riesgo',
        'Incitacion al odio contra un grupo protegido',
        'Spam y estafas'
    ]

    for category in categories:
        ReportCategory.objects.get_or_create(name=category, type_categorie='users')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reportcategory_name'),
    ]

    operations = [
        migrations.RunPython(create_report_categories_reviews),
        migrations.RunPython(create_report_categories_posts),
        migrations.RunPython(create_report_categories_users),
    ]
