# Generated by Django 5.1.2 on 2025-02-05 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reportcategory_type_categorie'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'reported_content_type', 'reported_object_id')},
        ),
    ]
