# Generated by Django 5.1.2 on 2025-02-03 04:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_userprofile_banstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BanStatus',
            new_name='UserProfile',
        ),
    ]
