# Generated by Django 5.1.2 on 2025-02-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_ban_status_userprofile_ban_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ban_until',
            new_name='banned_until',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ban_status',
            new_name='is_banned',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
    ]
