# Generated by Django 5.1.2 on 2025-02-13 02:14

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_ban_until_userprofile_banned_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='BanStatus',
        ),
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_ban_until_userprofile_banned_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('dni', models.IntegerField(db_column='dni')),
                ('email', models.TextField()),
                ('descripcion', models.TextField()),
                ('estadotrabajo', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('inactivo', 'Inactivo')], db_column='estadoTrabajo', default='disponible', max_length=20)),
                ('cvlink', models.FileField(blank=True, upload_to='cv/')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesion')),
            ],
        ),
    ]
