# Generated by Django 5.1.2 on 2024-10-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_review_code_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
