# Generated by Django 5.1.2 on 2025-02-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profesion_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='email',
        ),
    ]
