# Generated by Django 5.1.2 on 2024-10-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
