# Generated by Django 5.1.2 on 2025-02-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_trabajador_dni_remove_trabajador_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesion',
            name='descripcion',
        ),
        migrations.CreateModel(
            name='Solictud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_trabajadores', models.ManyToManyField(related_name='solicitudes', to='api.trabajador')),
            ],
        ),
    ]
