# Generated by Django 5.1.2 on 2025-02-13 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_profesion_descripcion_solictud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solictud',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='solictud',
            name='fecha_inicio',
        ),
    ]
