# Generated by Django 5.1.2 on 2024-10-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avg_ratings',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
