# Generated by Django 5.1.2 on 2025-02-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_solictud_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solictud',
            new_name='Solicitud',
        ),
    ]
