# Generated by Django 5.1.2 on 2025-02-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_userprofile_banstatus'),
        ('api', '0013_rename_solictud_solicitud'),
    ]

    operations = [
    ]
