version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Esto permite que los cambios en el código se reflejen sin necesidad de reconstruir
    ports:
      - "8000:8000"
  
  frontend:
    build:
      context: ./argy_reviews/frontend
    volumes:
      - ./argy_reviews/frontend:/app
    ports:
      - "3000:3000"  # Cambia según el puerto que utilice tu aplicación React
    command: npm run dev  # Asegúrate de que este comando inicie tu aplicación React