site_name: Documentacion de ARGY Reviews

nav:
  - Getting started: index.md
  - Guia para desarrollo de las interacciones: api.md

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
        
  features:
    - navigations.tabs
    - vavigations.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tabs.annotation
    - content.code.copy

  language: es

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - callouts
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google